dependencies {
  api deps.'gson'
  api project(path: ':coral-hive')
  api project(path: ':shading:coral-trino-parser', configuration: 'shadow')

  testImplementation(deps.'hive'.'hive-exec-core') {
    exclude group: 'org.apache.avro', module: 'avro-tools'
    // Exclude bundled Calcite from Hive to use LinkedIn Calcite fork
    exclude group: 'org.apache.calcite', module: 'calcite-core'
    exclude group: 'org.apache.calcite', module: 'calcite-avatica'
    exclude group: 'org.apache.calcite.avatica', module: 'avatica-core'
  }

  testImplementation deps.'hadoop'.'hadoop-mapreduce-client-common'
  testImplementation deps.'kryo'
  testImplementation deps.'jetbrains'
}
