apply plugin: 'antlr'

dependencies {
  antlr deps.'antlr'
  api project(path: ':coral-common')
  api deps.'ivy'

  // required for hiveSQL parser code
  api deps.'antlr-runtime'

  testImplementation(deps.'hive'.'hive-exec-core') {
    exclude group: 'org.apache.avro', module: 'avro-tools'
    // Exclude bundled Calcite from Hive to use LinkedIn Calcite fork
    exclude group: 'org.apache.calcite', module: 'calcite-core'
    exclude group: 'org.apache.calcite', module: 'calcite-avatica'
    exclude group: 'org.apache.calcite.avatica', module: 'avatica-core'
  }

  testImplementation deps.'hadoop'.'hadoop-mapreduce-client-core'
  testImplementation deps.'kryo'

  // Mockito for mocking in tests
  testImplementation 'org.mockito:mockito-core:2.28.2'
}

sourceSets.main.antlr.srcDirs = ['src/main/antlr/roots']

generateGrammarSource {
  arguments += [
    '-lib',
    'src/main/antlr/imports'
  ]}
