import com.github.jengelman.gradle.plugins.shadow.tasks.ConfigureShadowRelocation
apply plugin: "java"
apply plugin: "com.github.johnrengelman.shadow"

// In Gradle 7+, compileOnly is not resolvable. Create a separate resolvable configuration
// for the shadow plugin to package the trino-parser classes.
configurations {
  shadowDeps {
    canBeResolved = true
    canBeConsumed = false
  }
}

dependencies {
  compileOnly 'io.trino:trino-parser:355'
  shadowDeps 'io.trino:trino-parser:355'
}

task relocateShadowJar(type: ConfigureShadowRelocation) {
  target = tasks.shadowJar
  prefix = 'coral.shading'
}

shadowJar {
  configurations = [
    project.configurations.shadowDeps
  ]
  dependsOn(relocateShadowJar)
}

// Rename shadow jar to original artifact name, so that 'coral-trino-parser-x.x.x.jar' itself is the shadow jar
jar {
  enabled = false
  dependsOn(shadowJar { archiveClassifier.set('') })
}
